site_name: 'Моделирование выбора заказов и объемов производства'
site_description: 'Алгоритмы лнейного прграммирования для отбора заказов и планирования производства для четырех продуктов на основе гидроксида алюминия.'
site_author: 'E Pogrebnyak'
docs_dir: docs/
repo_name: 'epogrebnyak/aloh3'
repo_url: 'https://github.com/epogrebnyak/aloh3'
edit_uri: ""
nav:
    - 'Начало': index.md

    - 'Модель':
       - 'Производство': production.md
       - 'Заказы': orders.md
       - 'Задача ЛП': linprog.md
       - 'Формулы': colab.md
       - 'Допущения': assumptions.md
       
    - 'Примеры':
       - 'Пример 0': example0.md
       - 'Пример 1': example1.md

    - 'Планы работ':   
      - 'Текущий этап': current.md
      - 'План развития': roadmap.md

theme:
  name: 'material'
  palette:
    primary: blue
  features:
    - tabs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences    
  - pymdownx.tasklist:
      custom_checkbox: true
