site_name: AlOH Optimisation
site_description: 'Отбор заказов и планирование производства для продуктов на основе гидроксида алюминия.'
site_author: 'E Pogrebnyak'
docs_dir: docs/
repo_name: 'epogrebnyak/aloh3'
repo_url: 'https://github.com/epogrebnyak/aloh3'
nav:
    - Home: index.md
theme:
  name: 'material'
